<?php slot::start('preamble') ?>
    <div class="restrictions">
        <h3><?=_('Software Distribution Conditions')?></h3>
        <p><?=_('The Bespoke Software Deployment Server (BeSDS) permits the Enterprise Client (EC) to create a customized and secured versions of Firefox and Thunderbird for internal deployment. Redistributing software customized by BeSDS to devices not owned by the EC is not permitted. By using or deploying software generated by the BeSDS, you understand and agree to this restriction.')?></p>
	<p><?=_('Redistributable versions of Firefox and Thunderbird are available from Mozilla, as per the <a target="_new" href="http://www.mozilla.org/MPL/">Mozilla Public License</a>.')?></p> 
        <p><?=sprintf(_('When deploying your customized application, the installer will be referred to as %1$s in the Add/Remove Programs window.'), html::specialchars($repack->title))?></p>

        <p><?=sprintf(_('If you have any questions about these conditions, please <a href="%1$s">contact us</a>.'), url::site('contact'))?></p>
    </div>
<?php slot::end() ?>
<?=View::factory('repacks/elements/confirm_release', array(
    'repack'     => $repack,
    'head_title' => _('release'),
    'crumbs'     => _('request release'),
    'message'    => _('Agree to these terms and release for this browser.'),
    'url'        => url::site(url::current()),
))->render()?>
