<?php slot::start('preamble') ?>
    <div class="restrictions">
        <h3><?=_('Software Distribution Conditions')?></h3>
        <p><?=_('The Bespoke Software Deployment Server (BeSDS) permits the Enterprise Client (EC) to create a customized and secured version of Firefox for internal enterprise deployment. Redistribution of software customized by BeSDS to devices not owned an operated by the EC is not permitted. By using or deploying software generated by the BeSDS, you understand and agree to this restriction. Redistributable versions of Firefox are available directly from Mozilla, in accordance with the <a target="_new" href="http://www.mozilla.org/foundation/trademarks/policy.html" alt="Mozilla Trademark Policy">Mozilla Trademark Policy</a> and the <a target="_new" href="http://www.mozilla.org/MPL/">Mozilla Public License</a>.')?></p> 
        <p><?=sprintf(_('When deploying your customized version of Firefox, the installer will be referred to as %1$s in the Add/Remove Programs window, to differentiate it from the other releases of Firefox.'), html::specialchars($repack->title))?></p>

        <p><?=sprintf(_('If you have any questions regarding these conditions, or need clarification on any of the items mentioned here, please <a href="%1$s">contact us</a>.'), url::site('contact'))?></p>
    </div>
<?php slot::end() ?>
<?=View::factory('thunderbird_repacks/elements/confirm', array(
    'repack'     => $repack,
    'head_title' => _('release'),
    'crumbs'     => _('request release'),
    'message'    => _('Agree to these terms and release for this mail client.'),
    'url'        => url::site(url::current()),
))->render()?>
